// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbox.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimPendingMessages = `-- name: ClaimPendingMessages :many
SELECT id, event_type, target_url, payload, status, attempts, max_attempts, next_retry_at, last_error, sent_at, tenant_id, created_by, created_at, updated_at FROM outb_outbox_messages
WHERE status IN ('pending', 'failed')
  AND next_retry_at <= NOW()
ORDER BY next_retry_at ASC
LIMIT 50
FOR UPDATE SKIP LOCKED
`

func (q *Queries) ClaimPendingMessages(ctx context.Context) ([]OutbOutboxMessage, error) {
	rows, err := q.db.Query(ctx, claimPendingMessages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OutbOutboxMessage{}
	for rows.Next() {
		var i OutbOutboxMessage
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.TargetUrl,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.MaxAttempts,
			&i.NextRetryAt,
			&i.LastError,
			&i.SentAt,
			&i.TenantID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countOutboxMessages = `-- name: CountOutboxMessages :one
SELECT COUNT(*) FROM outb_outbox_messages
WHERE ($1::text IS NULL OR tenant_id = $1)
  AND ($2::text   IS NULL OR status     = $2)
  AND ($3::text IS NULL OR event_type = $3)
`

type CountOutboxMessagesParams struct {
	TenantID  pgtype.Text `json:"tenant_id"`
	Status    pgtype.Text `json:"status"`
	EventType pgtype.Text `json:"event_type"`
}

func (q *Queries) CountOutboxMessages(ctx context.Context, arg CountOutboxMessagesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOutboxMessages, arg.TenantID, arg.Status, arg.EventType)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOutboxMessage = `-- name: CreateOutboxMessage :one
INSERT INTO outb_outbox_messages (
    event_type,
    target_url,
    payload,
    max_attempts,
    tenant_id,
    created_by
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, event_type, target_url, payload, status, attempts, max_attempts, next_retry_at, last_error, sent_at, tenant_id, created_by, created_at, updated_at
`

type CreateOutboxMessageParams struct {
	EventType   string      `json:"event_type"`
	TargetUrl   string      `json:"target_url"`
	Payload     []byte      `json:"payload"`
	MaxAttempts int32       `json:"max_attempts"`
	TenantID    pgtype.Text `json:"tenant_id"`
	CreatedBy   pgtype.Text `json:"created_by"`
}

func (q *Queries) CreateOutboxMessage(ctx context.Context, arg CreateOutboxMessageParams) (OutbOutboxMessage, error) {
	row := q.db.QueryRow(ctx, createOutboxMessage,
		arg.EventType,
		arg.TargetUrl,
		arg.Payload,
		arg.MaxAttempts,
		arg.TenantID,
		arg.CreatedBy,
	)
	var i OutbOutboxMessage
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.TargetUrl,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.MaxAttempts,
		&i.NextRetryAt,
		&i.LastError,
		&i.SentAt,
		&i.TenantID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOutboxMessage = `-- name: DeleteOutboxMessage :exec
DELETE FROM outb_outbox_messages WHERE id = $1
`

func (q *Queries) DeleteOutboxMessage(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteOutboxMessage, id)
	return err
}

const getOutboxMessageByID = `-- name: GetOutboxMessageByID :one
SELECT id, event_type, target_url, payload, status, attempts, max_attempts, next_retry_at, last_error, sent_at, tenant_id, created_by, created_at, updated_at FROM outb_outbox_messages WHERE id = $1
`

func (q *Queries) GetOutboxMessageByID(ctx context.Context, id uuid.UUID) (OutbOutboxMessage, error) {
	row := q.db.QueryRow(ctx, getOutboxMessageByID, id)
	var i OutbOutboxMessage
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.TargetUrl,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.MaxAttempts,
		&i.NextRetryAt,
		&i.LastError,
		&i.SentAt,
		&i.TenantID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOutboxMessages = `-- name: ListOutboxMessages :many
SELECT id, event_type, target_url, payload, status, attempts, max_attempts, next_retry_at, last_error, sent_at, tenant_id, created_by, created_at, updated_at FROM outb_outbox_messages
WHERE ($1::text IS NULL OR tenant_id = $1)
  AND ($2::text   IS NULL OR status     = $2)
  AND ($3::text IS NULL OR event_type = $3)
ORDER BY created_at DESC
LIMIT  $5::int
OFFSET $4::int
`

type ListOutboxMessagesParams struct {
	TenantID  pgtype.Text `json:"tenant_id"`
	Status    pgtype.Text `json:"status"`
	EventType pgtype.Text `json:"event_type"`
	Offset    int32       `json:"offset"`
	Limit     int32       `json:"limit"`
}

func (q *Queries) ListOutboxMessages(ctx context.Context, arg ListOutboxMessagesParams) ([]OutbOutboxMessage, error) {
	rows, err := q.db.Query(ctx, listOutboxMessages,
		arg.TenantID,
		arg.Status,
		arg.EventType,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OutbOutboxMessage{}
	for rows.Next() {
		var i OutbOutboxMessage
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.TargetUrl,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.MaxAttempts,
			&i.NextRetryAt,
			&i.LastError,
			&i.SentAt,
			&i.TenantID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxMessageFailed = `-- name: MarkOutboxMessageFailed :one
UPDATE outb_outbox_messages
SET status        = $2,
    attempts      = $3,
    last_error    = $4,
    next_retry_at = $5,
    updated_at    = NOW()
WHERE id = $1
RETURNING id, event_type, target_url, payload, status, attempts, max_attempts, next_retry_at, last_error, sent_at, tenant_id, created_by, created_at, updated_at
`

type MarkOutboxMessageFailedParams struct {
	ID          uuid.UUID   `json:"id"`
	Status      string      `json:"status"`
	Attempts    int32       `json:"attempts"`
	LastError   pgtype.Text `json:"last_error"`
	NextRetryAt time.Time   `json:"next_retry_at"`
}

func (q *Queries) MarkOutboxMessageFailed(ctx context.Context, arg MarkOutboxMessageFailedParams) (OutbOutboxMessage, error) {
	row := q.db.QueryRow(ctx, markOutboxMessageFailed,
		arg.ID,
		arg.Status,
		arg.Attempts,
		arg.LastError,
		arg.NextRetryAt,
	)
	var i OutbOutboxMessage
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.TargetUrl,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.MaxAttempts,
		&i.NextRetryAt,
		&i.LastError,
		&i.SentAt,
		&i.TenantID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markOutboxMessageSent = `-- name: MarkOutboxMessageSent :one
UPDATE outb_outbox_messages
SET status   = 'sent',
    sent_at  = NOW(),
    updated_at = NOW()
WHERE id = $1
RETURNING id, event_type, target_url, payload, status, attempts, max_attempts, next_retry_at, last_error, sent_at, tenant_id, created_by, created_at, updated_at
`

func (q *Queries) MarkOutboxMessageSent(ctx context.Context, id uuid.UUID) (OutbOutboxMessage, error) {
	row := q.db.QueryRow(ctx, markOutboxMessageSent, id)
	var i OutbOutboxMessage
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.TargetUrl,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.MaxAttempts,
		&i.NextRetryAt,
		&i.LastError,
		&i.SentAt,
		&i.TenantID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resetOutboxMessage = `-- name: ResetOutboxMessage :one
UPDATE outb_outbox_messages
SET status        = 'pending',
    attempts      = 0,
    last_error    = NULL,
    next_retry_at = NOW(),
    sent_at       = NULL,
    updated_at    = NOW()
WHERE id = $1
RETURNING id, event_type, target_url, payload, status, attempts, max_attempts, next_retry_at, last_error, sent_at, tenant_id, created_by, created_at, updated_at
`

func (q *Queries) ResetOutboxMessage(ctx context.Context, id uuid.UUID) (OutbOutboxMessage, error) {
	row := q.db.QueryRow(ctx, resetOutboxMessage, id)
	var i OutbOutboxMessage
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.TargetUrl,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.MaxAttempts,
		&i.NextRetryAt,
		&i.LastError,
		&i.SentAt,
		&i.TenantID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
