// Package outbox provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package outbox

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for OutboxMessageStatus.
const (
	Dead    OutboxMessageStatus = "dead"
	Failed  OutboxMessageStatus = "failed"
	Pending OutboxMessageStatus = "pending"
	Sent    OutboxMessageStatus = "sent"
)

// OutboxMessage defines model for OutboxMessage.
type OutboxMessage struct {
	// Attempts Number of delivery attempts made so far
	Attempts  int       `json:"attempts"`
	CreatedAt time.Time `json:"created_at"`
	CreatedBy *string   `json:"created_by"`

	// EventType Identifies the kind of outbound call (e.g. trainer_session_feedback)
	EventType string             `json:"event_type"`
	Id        openapi_types.UUID `json:"id"`

	// LastError Error message from the last failed attempt
	LastError *string `json:"last_error"`

	// MaxAttempts Maximum attempts before marking as dead
	MaxAttempts int       `json:"max_attempts"`
	NextRetryAt time.Time `json:"next_retry_at"`

	// Payload Arbitrary JSON payload persisted at enqueue time
	Payload *map[string]interface{} `json:"payload,omitempty"`
	SentAt  *time.Time              `json:"sent_at"`

	// Status Delivery status of an outbox message
	Status OutboxMessageStatus `json:"status"`

	// TargetUrl HTTP endpoint that receives the POST
	TargetUrl string    `json:"target_url"`
	TenantId  *string   `json:"tenant_id"`
	UpdatedAt time.Time `json:"updated_at"`
}

// OutboxMessageStatus Delivery status of an outbox message
type OutboxMessageStatus string
